routes/web.php
<?php

Route::redirect('/', '/login');
Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});

Auth::routes();
// KG 27/01 Start
Route::get('/events-registeration', 'Auth\RegisterController@eventsRegisteration')->name('eventsRegisteration');
Route::post('/eventsRegisterationSave', 'Auth\RegisterController@register')->name('eventsRegisterationSave');
// KG 27/01 ENd
Route::get('userVerification/{token}', 'UserVerificationController@approve')->name('userVerification');
// Admin
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => []], function () {
Route::post('/users/media', 'UsersController@storeMedia')->name('users.storeMedia');
    Route::post('/approval', 'ApprovalController@index')->name('users.approval');
    Route::post('/installment', 'ApprovalController@installment')->name('users.installment');
    Route::post('/disapproval', 'ApprovalController@finaldisapproval')->name('users.disapproval');
});

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('user-alerts/read', 'UserAlertsController@read');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::post('users/verify', 'UsersController@verify')->name('users.verify');
    Route::post('users/ckmedia', 'UsersController@storeCKEditorImages')->name('users.storeCKEditorImages');
    Route::post('users/parse-csv-import', 'UsersController@parseCsvImport')->name('users.parseCsvImport');
    Route::post('users/process-csv-import', 'UsersController@processCsvImport')->name('users.processCsvImport');
    Route::resource('users', 'UsersController');
    // Lectures
    Route::delete('lectures/destroy', 'LecturesController@massDestroy')->name('lectures.massDestroy');
    Route::post('lectures/media', 'LecturesController@storeMedia')->name('lectures.storeMedia');
    Route::post('lectures/ckmedia', 'LecturesController@storeCKEditorImages')->name('lectures.storeCKEditorImages');
    Route::resource('lectures', 'LecturesController');

    // SystemEmails
    Route::delete('system-emails/destroy', 'SystemEmailsController@massDestroy')->name('system-emails.massDestroy');
    Route::post('system-emails/media', 'SystemEmailsController@storeMedia')->name('system-emails.storeMedia');
    Route::post('system-emails/ckmedia', 'SystemEmailsController@storeCKEditorImages')->name('system-emails.storeCKEditorImages');
    Route::resource('system-emails', 'SystemEmailsController');

    // UserLogs
    Route::delete('user-logs/destroy', 'UserLogsController@massDestroy')->name('user-logs.massDestroy');
    Route::post('user-logs/media', 'UserLogsController@storeMedia')->name('user-logs.storeMedia');
    Route::post('user-logs/ckmedia', 'UserLogsController@storeCKEditorImages')->name('user-logs.storeCKEditorImages');
    Route::resource('user-logs', 'UserLogsController');


    // Route::get('system-emails/testmail', 'SystemEmailsController@testmail')->name('system-emails.testmail');
    Route::get('testmail2', 'SystemEmailsController@testmail')->name('system-emails.testmail');

    // User Alerts
    Route::delete('user-alerts/destroy', 'UserAlertsController@massDestroy')->name('user-alerts.massDestroy');
    Route::resource('user-alerts', 'UserAlertsController', ['except' => ['edit', 'update']]);

    // Faq Categories
    Route::delete('faq-categories/destroy', 'FaqCategoryController@massDestroy')->name('faq-categories.massDestroy');
    Route::resource('faq-categories', 'FaqCategoryController');

    // Faq Questions
    Route::delete('faq-questions/destroy', 'FaqQuestionController@massDestroy')->name('faq-questions.massDestroy');
    Route::resource('faq-questions', 'FaqQuestionController');

    // Payments
    Route::resource('payments', 'PaymentController', ['except' => ['destroy']]);
    Route::get('lectures-payments', 'PaymentController@lectures')->name('payments.lectures');

    // Pay Nows
    Route::get('store-payments', 'PaymentController@add')->name('payments.add-store');
    Route::get('payment/cancel', 'PaymentController@cancel')->name('payments.cancel');
    Route::get('payment/error', 'PaymentController@error')->name('payments.error');
    Route::post('pay-nows', 'PayNowController@index');
   // Route::resource('pay-nows', 'PayNowController', ['except' => ['create', 'store', 'edit', 'update', 'show', 'destroy']]);
    Route::get('messenger', 'MessengerController@index')->name('messenger.index');
    Route::get('unpaid/send-email', 'UnpaidApplicantsController@index')->name('unpaid.send');
    Route::get('messenger/create', 'MessengerController@createTopic')->name('messenger.createTopic');
    Route::post('messenger', 'MessengerController@storeTopic')->name('messenger.storeTopic');
    Route::get('messenger/inbox', 'MessengerController@showInbox')->name('messenger.showInbox');
    Route::get('messenger/outbox', 'MessengerController@showOutbox')->name('messenger.showOutbox');
    Route::get('messenger/{topic}', 'MessengerController@showMessages')->name('messenger.showMessages');
    Route::delete('messenger/{topic}', 'MessengerController@destroyTopic')->name('messenger.destroyTopic');
    Route::post('messenger/{topic}/reply', 'MessengerController@replyToTopic')->name('messenger.reply');
    Route::get('messenger/{topic}/reply', 'MessengerController@showReply')->name('messenger.showReply');

    Route::get('binding-student', 'bindingController@index')->name('student.binding');
    Route::get('Unchecked-student', 'UncheckedController@index')->name('student.Unchecked');
    Route::get('withdrawal-student', 'withdrawalController@index')->name('student.withdrawal');
    Route::get('approved-student', 'approvedController@index')->name('student.approved');
    Route::get('disapproved-student', 'disapprovedController@index')->name('student.disapproved');
    Route::get('Unverified-student', 'UnverifiedController@index')->name('student.Unverified');

    Route::get('Unchecked-visitor', 'UncheckedController@visitors')->name('visitor.Unchecked');
    Route::get('approved-visitor', 'approvedController@visitors')->name('visitor.approved');
    Route::get('Unverified-visitor', 'UnverifiedController@visitors')->name('visitor.Unverified');

    // KG Start
    Route::get('payment', 'PaypalController@index');
    Route::post('charge', 'PaypalController@charge');
    Route::get('paymentsuccess', 'PaypalController@payment_success');
    Route::get('paymenterror', 'PaypalController@payment_error');
    // KG End
});
Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
// Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
        Route::post('profile', 'ChangePasswordController@updateProfile')->name('password.updateProfile');
        Route::post('profile/destroy', 'ChangePasswordController@destroy')->name('password.destroyProfile');
    }
});

app/Models/SystemEmail.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;
use Spatie\MediaLibrary\MediaCollections\Models\Media;
use \DateTimeInterface;

class SystemEmail extends Model implements HasMedia
{
    use SoftDeletes, InteractsWithMedia, HasFactory;

    public $table = 'system_emails';

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'name',
        'slug',
        'subject',
        'message',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }

    public function registerMediaConversions(Media $media = null): void
    {
        $this->addMediaConversion('thumb')->fit('crop', 50, 50);
        $this->addMediaConversion('preview')->fit('crop', 120, 120);
    }

    public function getDateAttribute($value)
    {
        return $value ? Carbon::parse($value)->format(config('panel.date_format')) : null;
    }

    public function setDateAttribute($value)
    {
        $this->attributes['date'] = $value ? Carbon::createFromFormat(config('panel.date_format'), $value)->format('Y-m-d') : null;
    }
}

app/Http/Controllers/Admin/SystemEmailsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Controllers\Traits\MediaUploadingTrait;
use App\Http\Requests\MassDestroySystemEmailRequest;
use App\Http\Requests\StoreSystemEmailRequest;
use App\Http\Requests\UpdateSystemEmailRequest;
use App\Models\SystemEmail;
use Gate;
use Illuminate\Http\Request;
use Spatie\MediaLibrary\MediaCollections\Models\Media;
use Symfony\Component\HttpFoundation\Response;

use Illuminate\Support\Facades\Auth;
use App\Models\User;
use Illuminate\Support\Facades\Notification;

use App\Notifications\VisitorWelcomeEmail;

class SystemEmailsController extends Controller
{
    use MediaUploadingTrait;

    public function index()
    {
        abort_if(Gate::denies('system_email_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $system_emails = SystemEmail::all();

        return view('admin.systemEmails.index', compact('system_emails'));
    }
    public function testmail(){
        $users = User::find(Auth::user()->id);
        Notification::send($users, new VisitorWelcomeEmail($users));
        die("----");
    }

    public function create()
    {
        abort_if(Gate::denies('system_email_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.systemEmails.create');
    }

    public function store(StoreSystemEmailRequest $request)
    {
        $system_email = SystemEmail::create($request->all());

        if ($media = $request->input('ck-media', false)) {
            Media::whereIn('id', $media)->update(['model_id' => $system_email->id]);
        }

        return redirect()->route('admin.system-emails.index');
    }

    public function edit(SystemEmail $system_email)
    {
        abort_if(Gate::denies('system_email_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.systemEmails.edit', compact('system_email'));
    }

    public function update(UpdateSystemEmailRequest $request, SystemEmail $system_email)
    {
        $system_email->update($request->all());

        return redirect()->route('admin.system-emails.index');
    }

    public function show(SystemEmail $system_email)
    {
        abort_if(Gate::denies('system_email_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.systemEmails.show', compact('system_email'));
    }

    public function destroy(SystemEmail $system_email)
    {
        abort_if(Gate::denies('system_email_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $system_email->delete();

        return back();
    }

    public function massDestroy(MassDestroySystemEmailRequest $request)
    {
        SystemEmail::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }

    public function storeCKEditorImages(Request $request)
    {
        abort_if(Gate::denies('system_email_create') && Gate::denies('system_email_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $model         = new SystemEmail();
        $model->id     = $request->input('crud_id', 0);
        $model->exists = true;
        $media         = $model->addMediaFromRequest('upload')->toMediaCollection('ck-media');

        return response()->json(['id' => $media->id, 'url' => $media->getUrl()], Response::HTTP_CREATED);
    }
}

resources/views/admin/systemEmails/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.system_email.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.system-emails.store") }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label class="required" for="name">{{ trans('cruds.system_email.fields.name') }}</label>
                <input class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" type="text" name="name" id="name" value="{{ old('name', '') }}" required>
                @if($errors->has('name'))
                    <div class="invalid-feedback">
                        {{ $errors->first('name') }}
                    </div>
                @endif
            </div>

            <div class="form-group">
                <label class="required" for="slug">{{ trans('cruds.system_email.fields.slug') }}</label>
                <input class="form-control {{ $errors->has('slug') ? 'is-invalid' : '' }}" type="text" name="slug" id="slug" value="{{ old('slug', '') }}" required>
                @if($errors->has('slug'))
                    <div class="invalid-feedback">
                        {{ $errors->first('slug') }}
                    </div>
                @endif
            </div>
            
            <div class="form-group">
                <label class="required" for="subject">{{ trans('cruds.system_email.fields.subject') }}</label>
                <input class="form-control {{ $errors->has('subject') ? 'is-invalid' : '' }}" type="text" name="subject" id="subject" value="{{ old('subject', '') }}" required>
                @if($errors->has('subject'))
                    <div class="invalid-feedback">
                        {{ $errors->first('subject') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.system_email.fields.subject_helper') }}</span>
            </div>
            
            <div class="form-group">
                <label for="message">{{ trans('cruds.system_email.fields.message') }}</label>
                <textarea class="form-control ckeditor {{ $errors->has('message') ? 'is-invalid' : '' }}" name="message" id="message">{!! old('message') !!}</textarea>
                @if($errors->has('message'))
                    <div class="invalid-feedback">
                        {{ $errors->first('message') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.system_email.fields.message_helper') }}</span>
            </div>

            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

@section('scripts')
<script>
    $(document).ready(function () {
  function SimpleUploadAdapter(editor) {
    editor.plugins.get('FileRepository').createUploadAdapter = function(loader) {
      return {
        upload: function() {
          return loader.file
            .then(function (file) {
              return new Promise(function(resolve, reject) {
                // Init request
                var xhr = new XMLHttpRequest();
                xhr.open('POST', '/admin/system-emails/ckmedia', true);
                xhr.setRequestHeader('x-csrf-token', window._token);
                xhr.setRequestHeader('Accept', 'application/json');
                xhr.responseType = 'json';

                // Init listeners
                var genericErrorText = `Couldn't upload file: ${ file.name }.`;
                xhr.addEventListener('error', function() { reject(genericErrorText) });
                xhr.addEventListener('abort', function() { reject() });
                xhr.addEventListener('load', function() {
                  var response = xhr.response;

                  if (!response || xhr.status !== 201) {
                    return reject(response && response.message ? `${genericErrorText}\n${xhr.status} ${response.message}` : `${genericErrorText}\n ${xhr.status} ${xhr.statusText}`);
                  }

                  $('form').append('<input type="hidden" name="ck-media[]" value="' + response.id + '">');

                  resolve({ default: response.url });
                });

                if (xhr.upload) {
                  xhr.upload.addEventListener('progress', function(e) {
                    if (e.lengthComputable) {
                      loader.uploadTotal = e.total;
                      loader.uploaded = e.loaded;
                    }
                  });
                }

                // Send request
                var data = new FormData();
                data.append('upload', file);
                data.append('crud_id', '{{ $system_email->id ?? 0 }}');
                xhr.send(data);
              });
            })
        }
      };
    }
  }

  var allEditors = document.querySelectorAll('.ckeditor');
  for (var i = 0; i < allEditors.length; ++i) {
    ClassicEditor.create(
      allEditors[i], {
        extraPlugins: [SimpleUploadAdapter]
      }
    );
  }
});
</script>

@endsection

resources/views/admin/systemEmails/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('cruds.system_email.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.system-emails.update", [$system_email->id]) }}" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label class="required" for="subject">{{ trans('cruds.system_email.fields.subject') }}</label>
                <input class="form-control {{ $errors->has('subject') ? 'is-invalid' : '' }}" type="text" name="subject" id="subject" value="{{ old('subject', $system_email->subject) }}" required>
                @if($errors->has('subject'))
                    <div class="invalid-feedback">
                        {{ $errors->first('subject') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.system_email.fields.subject_helper') }}</span>
            </div>
            
            <div class="form-group">
                <label for="message">{{ trans('cruds.system_email.fields.message') }}</label>
                <textarea class="form-control ckeditor {{ $errors->has('message') ? 'is-invalid' : '' }}" name="message" id="message">{!! old('message', $system_email->message) !!}</textarea>
                @if($errors->has('message'))
                    <div class="invalid-feedback">
                        {{ $errors->first('message') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.system_email.fields.message_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

@section('scripts')
<script>
    $(document).ready(function () {
  function SimpleUploadAdapter(editor) {
    editor.plugins.get('FileRepository').createUploadAdapter = function(loader) {
      return {
        upload: function() {
          return loader.file
            .then(function (file) {
              return new Promise(function(resolve, reject) {
                // Init request
                var xhr = new XMLHttpRequest();
                xhr.open('POST', '/admin/system-emails/ckmedia', true);
                xhr.setRequestHeader('x-csrf-token', window._token);
                xhr.setRequestHeader('Accept', 'application/json');
                xhr.responseType = 'json';

                // Init listeners
                var genericErrorText = `Couldn't upload file: ${ file.name }.`;
                xhr.addEventListener('error', function() { reject(genericErrorText) });
                xhr.addEventListener('abort', function() { reject() });
                xhr.addEventListener('load', function() {
                  var response = xhr.response;

                  if (!response || xhr.status !== 201) {
                    return reject(response && response.message ? `${genericErrorText}\n${xhr.status} ${response.message}` : `${genericErrorText}\n ${xhr.status} ${xhr.statusText}`);
                  }

                  $('form').append('<input type="hidden" name="ck-media[]" value="' + response.id + '">');

                  resolve({ default: response.url });
                });

                if (xhr.upload) {
                  xhr.upload.addEventListener('progress', function(e) {
                    if (e.lengthComputable) {
                      loader.uploadTotal = e.total;
                      loader.uploaded = e.loaded;
                    }
                  });
                }

                // Send request
                var data = new FormData();
                data.append('upload', file);
                data.append('crud_id', '{{ $systen_email->id ?? 0 }}');
                xhr.send(data);
              });
            })
        }
      };
    }
  }

  var allEditors = document.querySelectorAll('.ckeditor');
  for (var i = 0; i < allEditors.length; ++i) {
    ClassicEditor.create(
      allEditors[i], {
        extraPlugins: [SimpleUploadAdapter]
      }
    );
  }
});
</script>

@endsection

resources/views/admin/systemEmails/index.blade.php
@extends('layouts.admin')
@section('content')
@can('system_email_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route('admin.system-emails.create') }}">
                {{ trans('global.add') }} {{ trans('cruds.system_email.title_singular') }}
            </a>
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('cruds.system_email.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-SystemEmail">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.system_email.fields.id') }}
                        </th>
                        <th>
                            {{ trans('cruds.system_email.fields.name') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                    <tr>
                        <td>
                        </td>
                        <td>
                            <input class="search" type="text" placeholder="{{ trans('global.search') }}">
                        </td>
                        <td>
                            <input class="search" type="text" placeholder="{{ trans('global.search') }}">
                        </td>
                        <td>
                        </td>
                    </tr>
                </thead>
                <tbody>
                    @foreach($system_emails as $key => $system_email)
                        <tr data-entry-id="{{ $system_email->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $system_email->id ?? '' }}
                            </td>
                            <td>
                                {{ $system_email->name ?? '' }}
                            </td>
                            <td>
                                @can('system_email_show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.system-emails.show', $system_email->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan

                                @can('system_email_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.system-emails.edit', $system_email->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan

                             

                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>



@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('system_email_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.system-emails.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    orderCellsTop: true,
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  let table = $('.datatable-SystemEmail:not(.ajaxTable)').DataTable({ buttons: dtButtons })
  $('a[data-toggle="tab"]').on('shown.bs.tab click', function(e){
      $($.fn.dataTable.tables(true)).DataTable()
          .columns.adjust();
  });
  
let visibleColumnsIndexes = null;
$('.datatable thead').on('input', '.search', function () {
      let strict = $(this).attr('strict') || false
      let value = strict && this.value ? "^" + this.value + "$" : this.value

      let index = $(this).parent().index()
      if (visibleColumnsIndexes !== null) {
        index = visibleColumnsIndexes[index]
      }

      table
        .column(index)
        .search(value, strict)
        .draw()
  });
table.on('column-visibility.dt', function(e, settings, column, state) {
      visibleColumnsIndexes = []
      table.columns(":visible").every(function(colIdx) {
          visibleColumnsIndexes.push(colIdx);
      });
  })
})

</script>
@endsection

resources/views/admin/systemEmails/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('cruds.system_email.title') }}
    </div>

    <div class="card-body">
        <div class="form-group">
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.system-emails.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>
                            {{ trans('cruds.system_email.fields.id') }}
                        </th>
                        <td>
                            {{ $system_email->id }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.system_email.fields.name') }}
                        </th>
                        <td>
                            {{ $system_email->name }}
                        </td>
                    </tr>
                    
                    
                    <tr>
                        <th>
                            {{ trans('cruds.system_email.fields.message') }}
                        </th>
                        <td>
                            {!! $system_email->message !!}
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.system-emails.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
        </div>
    </div>
</div>



@endsection